### ISSUE TITLE
Description sometimes has HTML special codes in it

### ISSUE THREAD

**Issue by michael-han** [michael-han/fun.do#11]
We need a function that replaces them with the intended characters.

![screen shot 2015-04-23 at 9 15 23 pm](https://cloud.githubusercontent.com/assets/3112255/7310655/e3b6aab0-e9fd-11e4-9043-2c39a23f0281.png)

Something might come from here:
http://stackoverflow.com/questions/784586/convert-special-characters-to-html-in-javascript

**Comment by lusilva** [comment]
I think I might have fixed this
