### ISSUE TITLE
A gray layer appears on top of the background map (Chrome - new-card-ui )

### ISSUE THREAD

**Issue by lusilva** [michael-han/fun.do#12]
Not sure if this has to do with any of the CSS that you guys changed

![screenshot from 2015-04-24 16 56 22](https://cloud.githubusercontent.com/assets/6611481/7328530/4b199432-eaa4-11e4-8024-ad107e214a76.png)

**Comment by michael-han** [comment]
This might just be something nina added accidentally, we'll assign it to her, hahaha.

**Comment by livadap** [comment]
lol yea I applied it to body...apparently not. I'll fix it



—

**Comment by michael-han** [comment]
:smile:
