### ISSUE TITLE
Price can be long sentence or not defined

### ISSUE THREAD

**Issue by lusilva** [michael-han/fun.do#13]
The price field can be a long sentence describing the price, or null, or just a numeric number or range. Not sure how we want to handle this. Thoughts?

![screenshot from 2015-04-24 16 56 22](https://cloud.githubusercontent.com/assets/6611481/7328577/936b3b46-eaa4-11e4-9b66-308ce2c3d550.png)

**Comment by michael-han** [comment]
Nina is going to be fixing this to parse whether it has a price or just omit it :)

**Comment by lusilva** [comment]
Fixed with new parsing of price
